### PR TITLE
Use Zend API wherever possible

### PR DESCRIPTION
**Pull request by sjinks**
Refs: https://github.com/phalcon/zephir/issues/1392

### CODE REVIEW

File: .travis.yml [hunk 1]
```diff
@@ -34,7 +34,7 @@ before_install:
 install:
   - git clone -q --depth=1 https://github.com/phalcon/zephir.git ./zephir
   - bash ./tests/install_zephir.sh
-  - zephir fullclean && zephir generate --backend=ZendEngine3
+  #- zephir fullclean && zephir generate --backend=ZendEngine3
```
Comment (sergeyklay) [inline .travis.yml]: I'm sorry for this :)

Comment (sergeyklay) [inline .travis.yml]: Also you can comment all Zephir-related stuff her to speed up builds

Comment (sjinks) [inline .travis.yml]: The code works locally, trying to make it work on Travis :-)

File: ext/kernel/fcall.c [hunk 2]
```diff
@@ -440,70 +247,62 @@ int zephir_call_user_function(zval *object_pp, zend_class_entry *obj_ce, zephir_
...
-#else
-		EG(scope) = old_scope;
+	status = zend_call_function(&fci, &fcic);
+
+#if PHP_VERSION_ID < 70100
+	EG(scope) = old_scope;
 #endif
 
-	if (!cache_entry || !*cache_entry) {
+	if (0 && (!cache_entry || !*cache_entry)) {
```
Comment (sergeyklay) [inline ext/kernel/fcall.c]: Are you sure? :)

Comment (sjinks) [inline ext/kernel/fcall.c]: Yes :-) I just wanted to make it work and re-introduce caching later.

I have replaced `zephir_fcall_populate_fci_cache` with a call to `zend_is_callable_ex` (mostly because it handles `zephir_fcall_ce` case incorrectly; in Phalcon `phalcon_fcall_populate_fci_cache` was a stripped down version of `zend_is_callable_check_func` + `zend_is_callable_check_class`)

This affects the way the cache key is generated, thus I will need to rewrite that piece of code anyway :-)

Comment (sergeyklay) [inline ext/kernel/fcall.c]: In general I like your approach. Let me know when it be ready to merge. I plan to collet in this repo ready to use code to pull it to Zephir codebase. Whether you are comfortable with this workflow?

Comment (sjinks) [inline ext/kernel/fcall.c]: Yes

Comment (sjinks) [inline ext/kernel/fcall.c]: The issue with the existing caching mechanism is that in reality `fcic.function_handler` depends on the calling and called scopes.

For example,

```php
class A
{
    public function test1()
    {
        $this->private_func();
    }

    public function __call() { /*... */ }

    private function private_func() {}
}

$a = new A();
$a->test1();
$a->private_func();
```

In this case both calls to `private_func` will use different handlers; the existing caching mechanism does not take this into account, and `$a->private_func()` might call `private_func()` instead of `__call`.

**Comment by sergeyklay** [comment]
@sjinks What do you think about many `-Wunused-variable` warnings? I propose to delete these variables at all

**Comment by sjinks** [comment]
Да, согласен, у меня по службе сейчас аврал, пару дней буду очень сильно занят.

**Comment by sergeyklay** [comment]
I've cleaned `zephir_call_class_method_aparams` in 886d675e46617a3d95fb0b83fe683aa08bfc9f93. 

1. It is not good idea to do such suggestions in runtime (for real app users). Better place for this - compiling/parsing stage.
2. The `possible_method`-logic does not implemented

**Comment by Jurigag** [comment]
Most of tests for phalcon and 7.1 with this are passing, on the other hand i have some other weird issue like pdo exception with too many connections?

**Comment by sergeyklay** [comment]
I've added new test for `group/fcall.zep`

So it does not work in PHP 7.1
> PHP Warning:  Cannot call func_get_args() dynamically

**Comment by sergeyklay** [comment]
Refs: https://github.com/php/php-src/commit/91f5940329fede8a26b64e99d4d6d858fe8654cc

**Comment by sjinks** [comment]
Hi guys,

Does anyone know how "slot caching" works in Zephir (in PHP, I think)? I would be grateful if someone could explain me so that I don't have to study the PHP code.

My concern is this: does "slot caching" take into account method visibility?

For example, if I have

```php
class A
{
    public function publicFunc() { $this->privateFunc(); }
    private function privateFunc() {}
}
```

then in this case:

```php
$a = new A()
$a->publicFunc();
$a->privateFunc();
```

the first call to `privateFunc` (from `publicFunc`) will be in the context of `A`, but the second call should trigger an error (or invocation of `__call`).

Thus the question is whether Zephir understands that both calls have different visibility contexts and won't try to use the same slot for both?

**Comment by sjinks** [comment]
```c
ZEND_API int zend_forbid_dynamic_call(const char *func_name) /* {{{ */
{
        zend_execute_data *ex = EG(current_execute_data);
        ZEND_ASSERT(ex != NULL && ex->func != NULL);

        if (ZEND_CALL_INFO(ex) & ZEND_CALL_DYNAMIC) {
                zend_error(E_WARNING, "Cannot call %s dynamically", func_name);
                return FAILURE;
        }

        return SUCCESS;
}
```

in `zend_call_function`:

```c
call = zend_vm_stack_push_call_frame(ZEND_CALL_TOP_FUNCTION | ZEND_CALL_DYNAMIC,
    func, fci->param_count, fci_cache->called_scope, fci->object);
```

Hmmm

**Comment by sergeyklay** [comment]
I hope it is the thing: https://github.com/phalcon/zephir/commit/8d2eeaf97106130e96ef8d06618710567ba7a405#diff-130e117262a24cbf89ce233ddbed7514R101

**Comment by sergeyklay** [comment]
```php
if ($method->isPrivate() || $method->isFinal() || $mustBeCached) {
    ...
}
```

**Comment by sergeyklay** [comment]
> zend_forbid_dynamic_call

yeah, right now I'm trying to understand this :)

**Comment by sjinks** [comment]
Well, as far as I understand Zend logic, you cannot call `func_num_args()` and company with PHP's `call_user_function` (ZE's `zend_call_function`).

The issue is that Zend Extensions are to use `zend_call_function` to call other functions.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/zephir/blob/master/Library/Cache/MethodCache.php#L171

**Comment by sjinks** [comment]
Suggested replacements:

func_num_args: ZEND_CALL_NUM_ARGS(execute_data);
get_defined_vars:
```c
zend_array *symbol_table = zend_rebuild_symbol_table();
if (symbol_table) {
    result = zend_array_dup(symbol_table);
}
else {
    ZVAL_NULL(result);
}
```

func_get_arg()/func_get_args(): maybe use `ZEND_API int _zend_get_parameters_array_ex(int param_count, zval *argument_array)`

**Comment by sergeyklay** [comment]
Well, lets do it :)

File: ext/kernel/fcall.c [hunk 3]
```diff
@@ -76,7 +76,7 @@ static ulong zephir_make_fcall_key(char **result, size_t *length, const zend_cla
 	ulong hash = 5381;
 
 #if PHP_VERSION_ID >= 70100
-	calling_scope = EG(fake_scope);
+	calling_scope = zend_get_executed_scope();
```
Comment (sergeyklay) [inline ext/kernel/fcall.c]: 👍

**Comment by sjinks** [comment]
@sergeyklay please take a look

**Comment by sjinks** [comment]
If it looks good, I will submit a PR with `Library/Optimizers/FunctionCall/FuncGetArgsOptimizer.php` to Zephir

**Comment by sergeyklay** [comment]
@sjinks Looks good to me

**Comment by sergeyklay** [comment]
Fixed in https://github.com/phalcon/zephir/pull/1415
